### ISSUE TITLE
Valhalla does not build on macOS with clang 14.0.0

### ISSUE THREAD

**Issue by dillona** [valhalla/valhalla#3846]
On commit d4c8c1ab39fcbcad91e54160692c0f0aa9ad36aa:

```
➜  build git:(master) clang --version
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: x86_64-apple-darwin22.1.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

```
➜  build git:(master) make
[  0%] Building CXX object src/midgard/CMakeFiles/valhalla-midgard.dir/logging.cc.o
/Users/dillona/dev/valhalla/src/midgard/logging.cc:42:3: error: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. [-Werror,-Wdeprecated-declarations]
  sprintf(&buffer.front(), "%04d/%02d/%02d %02d:%02d:%09.6f", gmt.tm_year + 1900, gmt.tm_mon + 1,
  ^
/Library/Developer/CommandLineTools/SDKs/MacOSX13.0.sdk/usr/include/stdio.h:188:1: note: 'sprintf' has been explicitly marked deprecated here
__deprecated_msg("This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead.")
^
/Library/Developer/CommandLineTools/SDKs/MacOSX13.0.sdk/usr/include/sys/cdefs.h:215:48: note: expanded from macro '__deprecated_msg'
        #define __deprecated_msg(_msg) __attribute__((__deprecated__(_msg)))
                                                      ^
1 error generated.
make[2]: *** [src/midgard/CMakeFiles/valhalla-midgard.dir/logging.cc.o] Error 1
make[1]: *** [src/midgard/CMakeFiles/valhalla-midgard.dir/all] Error 2
make: *** [all] Error 2
```
