### ISSUE TITLE
 404  Not Found : ubuntu jammy Release

### ISSUE THREAD

**Issue by shkmhd7** [valhalla/valhalla#3725]
I am getting error after adding repository to ubuntu 22.0 server 

**sudo add-apt-repository ppa:kevinkreiser/prime-server**

```
Repository: 'deb https://ppa.launchpadcontent.net/kevinkreiser/prime-server/ubuntu/ jammy main'
Description:
A non-blocking (web)server API for distributed computing and SOA based on zeromq
More info: https://launchpad.net/~kevinkreiser/+archive/ubuntu/prime-server
Adding repository.
Press [ENTER] to continue or Ctrl-c to cancel.
Found existing deb entry in /etc/apt/sources.list.d/kevinkreiser-ubuntu-prime-server-jammy.list
Adding deb entry to /etc/apt/sources.list.d/kevinkreiser-ubuntu-prime-server-jammy.list
Found existing deb-src entry in /etc/apt/sources.list.d/kevinkreiser-ubuntu-prime-server-jammy.list
Adding disabled deb-src entry to /etc/apt/sources.list.d/kevinkreiser-ubuntu-prime-server-jammy.list
Adding key to /etc/apt/trusted.gpg.d/kevinkreiser-ubuntu-prime-server.gpg with fingerprint A88FE0A86A01FE708299FF30D0155F52B2F73663
Hit:1 http://apt.postgresql.org/pub/repos/apt jammy-pgdg InRelease
Hit:2 https://deb.nodesource.com/node_14.x jammy InRelease
Ign:3 https://ppa.launchpadcontent.net/kevinkreiser/prime-server/ubuntu jammy InRelease
Hit:4 http://us.archive.ubuntu.com/ubuntu jammy InRelease
Hit:5 http://us.archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:6 https://ppa.launchpadcontent.net/osmadmins/ppa/ubuntu jammy InRelease
Hit:7 http://us.archive.ubuntu.com/ubuntu jammy-backports InRelease
Ign:8 https://ppa.launchpadcontent.net/valhalla-core/valhalla/ubuntu jammy InRelease
Hit:9 http://us.archive.ubuntu.com/ubuntu jammy-security InRelease
Ign:10 https://ppa.launchpadcontent.net/valhalla-routing/valhalla/ubuntu jammy InRelease
Err:11 https://ppa.launchpadcontent.net/kevinkreiser/prime-server/ubuntu jammy Release
  404  Not Found [IP: 2620:2d:4000:1::3e 443]
Err:12 https://ppa.launchpadcontent.net/valhalla-core/valhalla/ubuntu jammy Release
  404  Not Found [IP: 2620:2d:4000:1::3e 443]
Err:13 https://ppa.launchpadcontent.net/valhalla-routing/valhalla/ubuntu jammy Release
  404  Not Found [IP: 2620:2d:4000:1::3e 443]
Reading package lists... Done
E: The repository 'https://ppa.launchpadcontent.net/kevinkreiser/prime-server/ubuntu jammy Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'https://ppa.launchpadcontent.net/valhalla-core/valhalla/ubuntu jammy Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'https://ppa.launchpadcontent.net/valhalla-routing/valhalla/ubuntu jammy Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

Thanks for advise . i don't think its a DNS issue .  because i am using a public server

**Comment by kevinkreiser** [comment]
You'll have to build prime server from source there is no jammy release yet

**Comment by shkmhd7** [comment]
Thanks your  support 

I am getting a different error while install from source  . Server Ubuntu 22

sudo make -C build install

```
make: Entering directory '/root/valhalla/build'
make[1]: Entering directory '/root/valhalla/build'
make[2]: Entering directory '/root/valhalla/build'
make[2]: Leaving directory '/root/valhalla/build'
[  3%] Built target valhalla-midgard
make[2]: Entering directory '/root/valhalla/build'
make[2]: Leaving directory '/root/valhalla/build'
[  9%] Built target valhalla-proto
make[2]: Entering directory '/root/valhalla/build'
make[2]: Leaving directory '/root/valhalla/build'
[ 25%] Built target valhalla-baldr
make[2]: Entering directory '/root/valhalla/build'
make[2]: Leaving directory '/root/valhalla/build'
[ 35%] Built target valhalla-mjolnir
make[2]: Entering directory '/root/valhalla/build'
make[2]: Leaving directory '/root/valhalla/build'
[ 38%] Built target valhalla-skadi
make[2]: Entering directory '/root/valhalla/build'
make[2]: Leaving directory '/root/valhalla/build'
[ 41%] Built target valhalla-sif
make[2]: Entering directory '/root/valhalla/build'
make[2]: Leaving directory '/root/valhalla/build'
[ 45%] Built target valhalla-loki
make[2]: Entering directory '/root/valhalla/build'
make[2]: Leaving directory '/root/valhalla/build'
[ 48%] Built target valhalla-meili
make[2]: Entering directory '/root/valhalla/build'
make[2]: Leaving directory '/root/valhalla/build'
[ 54%] Built target valhalla-odin
make[2]: Entering directory '/root/valhalla/build'
make[2]: Leaving directory '/root/valhalla/build'
[ 61%] Built target valhalla-thor
make[2]: Entering directory '/root/valhalla/build'
make[2]: Leaving directory '/root/valhalla/build'
[ 64%] Built target valhalla-tyr
make[2]: Entering directory '/root/valhalla/build'
make[2]: Leaving directory '/root/valhalla/build'
[ 64%] Built target valhalla
make[2]: Entering directory '/root/valhalla/build'
make[2]: Leaving directory '/root/valhalla/build'
[ 64%] Built target valhalla_run_map_match
make[2]: Entering directory '/root/valhalla/build'
make[2]: Leaving directory '/root/valhalla/build'
[ 64%] Built target valhalla_benchmark_loki
make[2]: Entering directory '/root/valhalla/build'
make[2]: Leaving directory '/root/valhalla/build'
[ 64%] Built target valhalla_benchmark_skadi
make[2]: Entering directory '/root/valhalla/build'
make[2]: Leaving directory '/root/valhalla/build'
[ 64%] Built target valhalla_run_isochrone
make[2]: Entering directory '/root/valhalla/build'
make[2]: Leaving directory '/root/valhalla/build'
[ 67%] Built target valhalla_run_route
make[2]: Entering directory '/root/valhalla/build'
make[2]: Leaving directory '/root/valhalla/build'
[ 67%] Built target valhalla_benchmark_adjacency_list
make[2]: Entering directory '/root/valhalla/build'
make[2]: Leaving directory '/root/valhalla/build'
[ 67%] Built target valhalla_run_matrix
make[2]: Entering directory '/root/valhalla/build'
make[2]: Leaving directory '/root/valhalla/build'
[ 70%] Built target valhalla_path_comparison
make[2]: Entering directory '/root/valhalla/build'
make[2]: Leaving directory '/root/valhalla/build'
[ 70%] Built target valhalla_export_edges
make[2]: Entering directory '/root/valhalla/build'
make[2]: Leaving directory '/root/valhalla/build'
[ 74%] Built target valhalla_expand_bounding_box
make[2]: Entering directory '/root/valhalla/build'
make[2]: Leaving directory '/root/valhalla/build'
[ 74%] Built target valhalla_service
make[2]: Entering directory '/root/valhalla/build'
make[2]: Leaving directory '/root/valhalla/build'
[ 74%] Built target valhalla_build_statistics
make[2]: Entering directory '/root/valhalla/build'
make[2]: Leaving directory '/root/valhalla/build'
[ 74%] Built target valhalla_ways_to_edges
make[2]: Entering directory '/root/valhalla/build'
make[2]: Leaving directory '/root/valhalla/build'
[ 74%] Built target valhalla_validate_transit
make[2]: Entering directory '/root/valhalla/build'
make[2]: Leaving directory '/root/valhalla/build'
[ 74%] Built target valhalla_benchmark_admins
make[2]: Entering directory '/root/valhalla/build'
make[2]: Leaving directory '/root/valhalla/build'
[ 77%] Built target valhalla_build_connectivity
make[2]: Entering directory '/root/valhalla/build'
make[2]: Leaving directory '/root/valhalla/build'
[ 77%] Built target valhalla_build_tiles
make[2]: Entering directory '/root/valhalla/build'
make[2]: Leaving directory '/root/valhalla/build'
make[2]: Entering directory '/root/valhalla/build'
[ 77%] Linking CXX executable valhalla_build_admins
/usr/bin/ld: src/libvalhalla.a(adminbuilder.cc.o): in function `valhalla::mjolnir::BuildAdminFromPBF(boost::property_tree::basic_ptree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)':
adminbuilder.cc:(.text+0x3eee): undefined reference to `geos::geom::Coordinate::Coordinate()'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/valhalla_build_admins.dir/build.make:108: valhalla_build_admins] Error 1
make[2]: Leaving directory '/root/valhalla/build'
make[1]: *** [CMakeFiles/Makefile2:1572: CMakeFiles/valhalla_build_admins.dir/all] Error 2
make[1]: Leaving directory '/root/valhalla/build'
make: *** [Makefile:156: all] Error 2
make: Leaving directory '/root/valhalla/build'
root@map:~/valhalla#

```

I could not find same type of error in google search  . thank for the help.

**Comment by M393** [comment]
The constructor is unfortunatly not available in every build of geos. But you can patch it.
```patch
diff --git a/src/mjolnir/adminbuilder.cc b/src/mjolnir/adminbuilder.cc
index d08af5abb..97d5b652d 100644
--- a/src/mjolnir/adminbuilder.cc
+++ b/src/mjolnir/adminbuilder.cc
@@ -409,7 +409,7 @@ void BuildAdminFromPBF(const boost::property_tree::ptree& pt,

           const PointLL ll = osm_admin_data.shape_map.at(ref_id);

-          Coordinate c;
+          Coordinate c{Coordinate::getNull()};
           c.x = ll.lng();
           c.y = ll.lat();
           coords->add(c, 0);
```

**Comment by nilsnolde** [comment]
Yeah it doesn’t build on 22.04 right now apparently, one of the main reasons @kevinkreiser set out to replace the geos C++ bindings with the C library in #3683

**Comment by kevinkreiser** [comment]
Exactly. Soonish we will merge a pr that makes it buildable

**Comment by shkmhd7** [comment]
> The constructor is unfortunately not available in every build of geos. But you can patch valhalla to make it work here.
> 
> ```diff
> diff --git a/src/mjolnir/adminbuilder.cc b/src/mjolnir/adminbuilder.cc
> index d08af5abb..97d5b652d 100644
> --- a/src/mjolnir/adminbuilder.cc
> +++ b/src/mjolnir/adminbuilder.cc
> @@ -409,7 +409,7 @@ void BuildAdminFromPBF(const boost::property_tree::ptree& pt,
> 
>            const PointLL ll = osm_admin_data.shape_map.at(ref_id);
> 
> -          Coordinate c;
> +          Coordinate c{Coordinate::getNull()};
>            c.x = ll.lng();
>            c.y = ll.lat();
>            coords->add(c, 0);
> ```

Thanks @M393  

This solution fixed Build issues . I hade to nano edit the file manually the file src/mjolnir/adminbuilder.cc . 

changed  **Coordinate c;** to   **Coordinate c{Coordinate::getNull()};**

Thanks to all .

**Comment by kevinkreiser** [comment]
It's not an easy fix the build of geos in jammy won't link. I'm porting to the c API which is stable and broken in another way in jammy but not in a way that will stop us from using it.
