### PR TITLE
fix: unused variable `max_way_id_file`

### PR DESCRIPTION
**Pull request by kinkard**
_Please don't force-push once you received the first review._

# Issue

```
$ cmake .. -DCMAKE_BUILD_TYPE=Release && cmake --build . -j 14
-- The CXX compiler identification is AppleClang 17.0.0.17000013
-- The C compiler identification is AppleClang 17.0.0.17000013
...
[32/58] Building CXX object src/mjolnir/CMakeFiles/valhalla-mjolnir.dir/util.cc.o
FAILED: [code=1] src/mjolnir/CMakeFiles/valhalla-mjolnir.dir/util.cc.o
valhalla/src/mjolnir/util.cc:38:19: error: unused variable 'max_way_id_file' [-Werror,-Wunused-const-variable]
   38 | const std::string max_way_id_file = "max_way_id.bin";
      |                   ^~~~~~~~~~~~~~~
1 error generated.
```

## Tasklist

 - [ ] Add tests
 - [ ] Add #fixes with the issue number that this PR addresses
 - [ ] Update the docs with any new request parameters or changes to behavior described
 - [ ] Update the [changelog](CHANGELOG.md)
 - [ ] If you made changes to the lua files, update the [taginfo](taginfo.json) too
 - [ ] If you made changes to a translation file, [update transifex](docs/docs/locales.md) too

## Requirements / Relations

 Link any requirements here. Other pull requests this PR is based on?

### CODE REVIEW

**Review by nilsnolde — APPROVED** [review]
when did we remove the logic for that? never heard..

**Comment by kinkard** [comment]
> when did we remove the logic for that? never heard..

Introduced in https://github.com/valhalla/valhalla/pull/6127 and then this file was removed in https://github.com/valhalla/valhalla/pull/6195
