### PR TITLE
fix: `-Werror` by clang in meili

### PR DESCRIPTION
**Pull request by kinkard**
This PR fixes compilation errors introduced in https://github.com/valhalla/valhalla/pull/5548

```
valhalla/src/meili/match_route.cc:13:6: error: unused function 'ValidateRoute' [-Werror,-Wunused-function]
   13 | bool ValidateRoute(baldr::GraphReader& graphreader,
      |      ^~~~~~~~~~~~~
1 error generated.
...
valhalla/valhalla/meili/transition_cost_model.h:93:8: error: private field 'match_on_restrictions_' is not used [-Werror,-Wunused-private-field]
   93 |   bool match_on_restrictions_{false};
      |        ^
1 error generated.
```

# Issue

What issue is this PR targeting? If there is no issue that addresses the problem, please open a corresponding issue and link it here.

## Tasklist

 - [ ] Add tests
 - [ ] Add #fixes with the issue number that this PR addresses
 - [ ] Update the docs with any new request parameters or changes to behavior described
 - [ ] Update the [changelog](CHANGELOG.md)
 - [ ] If you made changes to the lua files, update the [taginfo](taginfo.json) too
 - [ ] If you made changes to a translation file, [update transifex](docs/docs/locales.md) too

## Requirements / Relations

 Link any requirements here. Other pull requests this PR is based on?

### CODE REVIEW

**Comment by kinkard** [comment]
```

/bin/bash: line 1: 22914 Bus error               (core dumped) /usr/bin/python3.12 -m unittest discover -s /home/runner/work/valhalla/valhalla/test/bindings/python -v > /home/runner/work/valhalla/valhalla/build/test/python_valhalla.log 2>&1
```
🤔

**Review by nilsnolde — APPROVED** [review]
