### PR TITLE
fix unique_ptr usage for GEOS 3.7

### LINKED ISSUE #1570: Unable to build with geos 3.7.0
Building master with geos 3.7.0 fails

```
Building CXX object CMakeFiles/valhalla_build_admins.dir/src/mjolnir/valhalla_build_admins.cc.o
In file included from /tmp/valhalla/src/mjolnir/valhalla_build_admins.cc:23:
/usr/include/geos/geom/Geometry.h:26:3: warning: #warning "The GEOS C++ API is unstable, please use the C API instead" [-Wcpp]
 # warning "The GEOS C++ API is unstable, please use the C API instead"
   ^~~~~~~
/usr/include/geos/geom/Geometry.h:27:3: warning: #warning "HINT: #include geos_c.h" [-Wcpp]
 # warning "HINT: #include geos_c.h"
   ^~~~~~~
/tmp/valhalla/src/mjolnir/valhalla_build_admins.cc: In function 'std::vector<std::__cxx11::basic_string<char> > GetWkts(std::unique_ptr<geos::geom::Geometry>&)':
/tmp/valhalla/src/mjolnir/valhalla_build_admins.cc:147:20: error: 'unique_ptr' is not a member of 'geos::geom::GeometryFactory'
   GeometryFactory::unique_ptr gf = GeometryFactory::create();
                    ^~~~~~~~~~
/tmp/valhalla/src/mjolnir/valhalla_build_admins.cc:164:35: error: 'gf' was not declared in this scope
       polys[totalpolys].polygon = gf->createPolygon(gf->createLinearRing(pline->getCoordinates()), 0);
                                   ^~
/tmp/valhalla/src/mjolnir/valhalla_build_admins.cc:230:21: error: 'gf' was not declared in this scope
       Polygon* poly(gf->createPolygon(polys[i].ring, interior.release()));
                     ^~
/tmp/valhalla/src/mjolnir/valhalla_build_admins.cc:236:41: error: 'gf' was not declared in this scope
     std::unique_ptr<Geometry> multipoly(gf->createMultiPolygon(polygons.release()));
                                         ^~
/tmp/valhalla/src/mjolnir/valhalla_build_admins.cc: In function 'void BuildAdminFromPBF(const ptree&, const std::vector<std::__cxx11::basic_string<char> >&)':
/tmp/valhalla/src/mjolnir/valhalla_build_admins.cc:426:20: error: 'unique_ptr' is not a member of 'geos::geom::GeometryFactory'
   GeometryFactory::unique_ptr gf = GeometryFactory::create();
                    ^~~~~~~~~~
/tmp/valhalla/src/mjolnir/valhalla_build_admins.cc:451:13: error: 'gf' was not declared in this scope
             gf->getCoordinateSequenceFactory()->create((size_t)0, (size_t)2));
             ^~
/tmp/valhalla/src/mjolnir/valhalla_build_admins.cc:473:41: error: 'gf' was not declared in this scope
         std::unique_ptr<Geometry> mline(gf->createMultiLineString(lines.release()));
                                         ^~
make[2]: *** [CMakeFiles/valhalla_build_admins.dir/build.make:63: CMakeFiles/valhalla_build_admins.dir/src/mjolnir/valhalla_build_admins.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:961: CMakeFiles/valhalla_build_admins.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
```

### PR DESCRIPTION
**Pull request by akstrfn**
# Issue
GeometryFactory::unique_ptr does not exist in GeometryFactory.h in GEOS 3.7:
https://github.com/libgeos/geos/blob/3.7/include/geos/geom/GeometryFactory.h#L80

Fixes #1570 (already had the correctly proposed fix in the issue)

## Tasklist

 - [ ] Add tests
 - [ ] Review - you must request approval to merge any PR to master
 - [X] Add #fixes with the issue number that this PR addresses
 - [ ] Generally use squash merge to rebase and clean comments before merging
 - [ ] Update the [changelog](CHANGELOG.md)
 - [ ] Update relevant [documentation](docs/README.md)

### CODE REVIEW

**Comment by kevinkreiser** [comment]
looks like the vesion of geos on our mac builds doesnt support this. @akstrfn can you exapnd the `#if`s to check the version of geos and only do this when the particular version supports it?

**Comment by akstrfn** [comment]
@kevinkreiser I didn't check the 3.6 branch :roll_eyes:, sry.

I think auto fits here nicely?

In 3.7 there is a warning that C++ API is [unstable](https://github.com/libgeos/geos/blob/master/NEWS#L32) :smile:

**Comment by kevinkreiser** [comment]
Nice, using auto is perfect!
