### ISSUE TITLE
Won't build on macos 10.12.4 due to sqlite3 linking error.

### ISSUE THREAD

**Issue by molind** [valhalla/valhalla#729]
Valhalla won't build from master thread on macOS 10.12.4 due to sqlite3 linking error. I do have sqlite3 installed from brew but it's keg-only by default.

Sqlite installed in the system is 3.16.0
```
bash-3.2$ /usr/bin/sqlite3 --version
3.16.0 2016-11-04 19:09:39 0e5ffd9123d6d2d2b8f3701e8a73cc98a3a7ff5f
```

```
Undefined symbols for architecture x86_64:
  "_sqlite3_enable_load_extension", referenced from:
      Benchmark(boost::property_tree::basic_ptree<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) in valhalla_benchmark_admins-valhalla_benchmark_admins.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [valhalla_benchmark_admins] Error 1
make[1]: *** Waiting for unfinished jobs....
ld: warning: directory not found for option '-L/usr/lib/x86_64-darwin16.5.0'
Undefined symbols for architecture x86_64:
  "_sqlite3_enable_load_extension", referenced from:
      BuildAdminFromPBF(boost::property_tree::basic_ptree<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) in valhalla_build_admins-valhalla_build_admins.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [valhalla_build_admins] Error 1
make: *** [check] Error 2
```

Makefile contains following lines:
```
SQLITE3_CFLAGS = -I/usr/include
SQLITE3_LDFLAGS = -L/usr/lib -lsqlite3
SQLITE3_VERSION = 3.16.0
```

**Comment by molind** [comment]
fixed by

`brew link sqlite3`

**Comment by kevinkreiser** [comment]
cool i'll add this to the macos section in the readme, does that sound appropriate?

**Comment by bryanSME** [comment]
> fixed by
> 
> `brew link sqlite3`

On Catalina this no longer works.

`Warning: Refusing to link macOS-provided software: sqlite`
