### ISSUE TITLE
Build failure on OpenBSD: loki/search.cc

### ISSUE THREAD

**Issue by bentley** [valhalla/valhalla#543]
valhalla-2.0.8 and -2.0.9 fail to build on OpenBSD amd64 with GCC 4.9.4. (valhalla-2.0.7 built fine.)

    c++ -DHAVE_CONFIG_H -I. -I./valhalla -pthread -I/usr/local/include -DBOOST_SPIRIT_THREADSAFE -DBOOST_NO_CXX11_SCOPED_ENUMS -I/usr/local/include -pthread -I/usr/include -I/usr/ports/pobj/valhalla-2.0.8/valhalla-2.0.8/valhalla -I/usr/ports/pobj/valhalla-2.0.8/valhalla-2.0.8/valhalla/proto -Igenfiles -I/usr/local/include/lua-5.3 -O2 -pipe -std=c++11 -MT src/loki/libvalhalla_la-search.lo -MD -MP -MF src/loki/.deps/libvalhalla_la-search.Tpo -c src/loki/search.cc -fPIC -DPIC -o src/loki/.libs/libvalhalla_la-search.o
    src/loki/search.cc: In function 'std::unordered_map<valhalla::baldr::Location, valhalla::baldr::PathLocation> valhalla::loki::Search(const std::vector<valhalla::baldr::Location>&, valhalla::baldr::GraphReader&, const EdgeFilter&, const NodeFilter&)':
    src/loki/search.cc:596:13: error: converting to 'std::unordered_map<valhalla::baldr::Location, valhalla::baldr::PathLocation>' from initializer list would use explicit constructor 'std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::unordered_map(std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::size_type, const hasher&, const key_equal&, const allocator_type&) [with _Key = valhalla::baldr::Location; _Tp = valhalla::baldr::PathLocation; _Hash = std::hash<valhalla::baldr::Location>; _Pred = std::equal_to<valhalla::baldr::Location>; _Alloc = std::allocator<std::pair<const valhalla::baldr::Location, valhalla::baldr::PathLocation> >; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::size_type = long unsigned int; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::hasher = std::hash<valhalla::baldr::Location>; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::key_equal = std::equal_to<valhalla::baldr::Location>; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::allocator_type = std::allocator<std::pair<const valhalla::baldr::Location, valhalla::baldr::PathLocation> >]'
         return {};
                 ^
    Error while executing c++ -DHAVE_CONFIG_H -I. -I./valhalla -pthread -I/usr/local/include -DBOOST_SPIRIT_THREADSAFE -DBOOST_NO_CXX11_SCOPED_ENUMS -I/usr/local/include -pthread -I/usr/include -I/usr/ports/pobj/valhalla-2.0.8/valhalla-2.0.8/valhalla -I/usr/ports/pobj/valhalla-2.0.8/valhalla-2.0.8/valhalla/proto -Igenfiles -I/usr/local/include/lua-5.3 -O2 -pipe -std=c++11 -MT src/loki/libvalhalla_la-search.lo -MD -MP -MF src/loki/.deps/libvalhalla_la-search.Tpo -c src/loki/search.cc -fPIC -DPIC -o src/loki/.libs/libvalhalla_la-search.o
    gmake[1]: *** [Makefile:4746: src/loki/libvalhalla_la-search.lo] Error 2
